version: '{build}'
branches:
  only:
  - prod
skip_tags: true
image: Visual Studio 2019
configuration: Release
init:
- cmd: >-
    @ECHO off

    FOR /f %%a IN ('powershell -Command "Get-Date -format yy.MM.dd.HHmm"') do set BUILD_VERSION=%%a
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(BUILD_VERSION)
  assembly_version: $(BUILD_VERSION)
  file_version: $(BUILD_VERSION)
environment:
  BUILD_VERSION: 0.0.0.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
install:
- ps: Install-Module -Name SignPath
build_script:
- cmd: >-
    CALL %APPVEYOR_BUILD_FOLDER%/build/sanity_check.bat

    CALL %APPVEYOR_BUILD_FOLDER%/build/build.bat


    REM Sign installer binaries

    SET PowerShellScriptPath=%APPVEYOR_BUILD_FOLDER%/build/sign.ps1

    PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '%PowerShellScriptPath%'";
test: off
artifacts:
- path: publish/windows.exe
  name: windows
- path: publish/linux_portable.zip
  name: linux_portable
- path: publish/osx_portable.zip
  name: mac_portable
- path: publish/windows_portable.zip
  name: windows_portable
deploy:
- provider: GitHub
  tag: $(BUILD_VERSION)
  release: $(BUILD_VERSION)
  auth_token:
    secure: WHpMKpgKBOBAZJtEykGiktPF6gfjlHZMati9bXH6xZZS12v72miRO5a6ORsxkU1n
  repository: waliarubal/Jaya
  artifact: publish/windows.exe,publish/linux_portable.zip,publish/osx_portable.zip,publish/windows_portable.zip
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: prod