version: '{build}'
branches:
  only:
  - prod
skip_tags: true
image: Visual Studio 2019
configuration: Release
init:
- cmd: >-
    @ECHO off

    FOR /f %%a IN ('powershell -Command "Get-Date -format yy.MM.dd.HHmm"') do set BUILD_VERSION=%%a
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(BUILD_VERSION)
  assembly_version: $(BUILD_VERSION)
  file_version: $(BUILD_VERSION)
environment:
  BUILD_VERSION: 0.0.0.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
install:
- ps: Install-Module -Name SignPath
build_script:
- cmd: >-
    CALL %APPVEYOR_BUILD_FOLDER%/build/sanity_check.bat

    CALL %APPVEYOR_BUILD_FOLDER%/build/build.bat
test: off
artifacts:
- path: publish/windows.exe
  name: windows
- path: publish/linux_portable.zip
  name: linux_portable
- path: publish/osx_portable.zip
  name: mac_portable
- path: publish/windows_portable.zip
  name: windows_portable
before_deploy:
- ps: >-
    Submit-SigningRequest `
      -InputArtifactPath "publish/windows.exe" `
      -CIUserToken "AEVquz4p/MFkP7KiMAEJMipcmYZZzXuavTXDTbZW6wPd" `
      -OrganizationId "ec7e0b29-bda8-4762-8956-49e0648546a2" `
      -ProjectKey "Jaya" `
      -SigningPolicyKey "test-signing" `
      -OutputArtifactPath "published_signed/windows.exe" `
      -WaitForCompletion

    Submit-SigningRequest `
      -InputArtifactPath "publish/linux_portable.zip" `
      -CIUserToken "AEVquz4p/MFkP7KiMAEJMipcmYZZzXuavTXDTbZW6wPd" `
      -OrganizationId "ec7e0b29-bda8-4762-8956-49e0648546a2" `
      -ProjectKey "Jaya" `
      -SigningPolicyKey "test-signing" `
      -OutputArtifactPath "published_signed/linux_portable.zip" `
      -WaitForCompletion

    Submit-SigningRequest `
      -InputArtifactPath "publish/osx_portable.zip" `
      -CIUserToken "AEVquz4p/MFkP7KiMAEJMipcmYZZzXuavTXDTbZW6wPd" `
      -OrganizationId "ec7e0b29-bda8-4762-8956-49e0648546a2" `
      -ProjectKey "Jaya" `
      -SigningPolicyKey "test-signing" `
      -OutputArtifactPath "published_signed/osx_portable.zip" `
      -WaitForCompletion

    Submit-SigningRequest `
      -InputArtifactPath "publish/windows_portable.zip" `
      -CIUserToken "AEVquz4p/MFkP7KiMAEJMipcmYZZzXuavTXDTbZW6wPd" `
      -OrganizationId "ec7e0b29-bda8-4762-8956-49e0648546a2" `
      -ProjectKey "Jaya" `
      -SigningPolicyKey "test-signing" `
      -OutputArtifactPath "published_signed/windows_portable.zip" `
      -WaitForCompletion
deploy:
- provider: GitHub
  tag: $(BUILD_VERSION)
  release: $(BUILD_VERSION)
  auth_token:
    secure: WHpMKpgKBOBAZJtEykGiktPF6gfjlHZMati9bXH6xZZS12v72miRO5a6ORsxkU1n
  repository: waliarubal/Jaya
  artifact: publish_signed/windows.exe,publish_signed/linux_portable.zip,publish_signed/osx_portable.zip,publish_signed/windows_portable.zip
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: prod