version: '{build}'
branches:
  only:
  - prod
skip_tags: true
image: Visual Studio 2019
configuration: Release
init:
- cmd: >-
    @ECHO off

    FOR /f %%a IN ('powershell -Command "Get-Date -format yy.MM.dd.HHmm"') do set BUILD_VERSION=%%a
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(BUILD_VERSION)
  assembly_version: $(BUILD_VERSION)
  file_version: $(BUILD_VERSION)
environment:
  BUILD_VERSION: 0.0.0.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- cmd: >-
    CALL %APPVEYOR_BUILD_FOLDER%/build/sanity_check.bat

    CALL %APPVEYOR_BUILD_FOLDER%/build/build.bat
test: off
artifacts:
- path: publish/windows.exe
  name: windows
- path: publish/linux_portable.zip
  name: linux_portable
- path: publish/osx_portable.zip
  name: mac_portable
- path: publish/windows_portable.zip
  name: windows_portable
deploy:
- provider: GitHub
  tag: $(BUILD_VERSION)
  release: $(BUILD_VERSION)
  description: Automated release for version $(BUILD_VERSION).
  auth_token:
    secure: UgS7u6/QF29WDtX3jzm9xC64vZ52V8yGYWAvpMW+h+95ghtdOHalzcmyemVTg28H
  repository: waliarubal/Jaya
  artifact: publish/windows.exe,publish/linux_portable.zip,publish/osx_portable.zip,publish/windows_portable.zip
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: prod